server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件的路径
  type-aliases-package: xyz.ceanie.entity   #加载所有实体类的路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml   #映射mapper所有的文件

spring:
  application:
    name: microsespringcloud-dept   #对外曝光的微服务的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #连接数据源的类型
    driver-class-name: com.mysql.jdbc.Driver  #mysql的驱动包
    url: jdbc:mysql://cdb-b1su98jp.gz.tencentcdb.com:10016/springcloud-learn  #连接数据库的名称
    username: root
    password: cjj19970921
    dbcp2:
      min-idle: 6  #连接池最小的连接数
      initial-size: 6 #初始化连接数
      max-idle: 6  #最大连接数
      max-wait-millis: 3000 #等待获取最大超时时间
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka #注入的地址 必须和7001中的地址一致
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microsespringcloud-dept8001-hystrix
    prefer-ip-address: true #显示ip地址

info:
 app.name: springcloud-learn  #工程名称
 company.name: www.ceanie.xyz  #公司名称
 build.artifactId: springcloud-provider-dept-hystrix-8001 #调用父工程build
 build.version: 1.0-SNAPSHOT
